import React from 'react';

export default function GovtSchemes({ crop, t }) {
  const cropName = t(crop.nameKey);
  
  return (
    <div className="govt-schemes glass-container" style={{marginTop: '40px', padding: '40px', textAlign: 'left', border: '1px solid rgba(16, 185, 129, 0.3)'}}>
      <div style={{display: 'flex', alignItems: 'center', gap: '15px', marginBottom: '25px'}}>
         <div style={{width: '50px', height: '50px', borderRadius: '12px', background: 'rgba(16, 185, 129, 0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.5rem'}}>🏛️</div>
         <h2 style={{color: 'white', margin: 0, fontSize: '1.8rem'}}>Govt Subsidies & Schemes for {cropName}</h2>
      </div>
      
      <p style={{color: 'var(--text-muted)', lineHeight: '1.6', fontSize: '1.05rem'}}>
        The Government of India provides massive financial support to promote commercial {cropName} cultivation. By leveraging these three central schemes, farmers can reduce their Capital Expenditure (CapEx) by up to 50%.
      </p>

      <div style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '20px', marginTop: '30px'}}>
          <div style={{background: 'rgba(255,255,255,0.03)', padding: '25px', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)'}}>
              <h3 style={{color: 'var(--accent-gold)', margin: '0 0 10px 0'}}>1. MIDH Scheme</h3>
              <p style={{color: 'var(--text-muted)', fontSize: '0.9rem', margin: 0, lineHeight: '1.5'}}>Mission for Integrated Development of Horticulture. Provides 40% to 50% subsidy on total project cost for high-value crops, including trellising and planting material.</p>
          </div>
          <div style={{background: 'rgba(255,255,255,0.03)', padding: '25px', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)'}}>
              <h3 style={{color: '#3b82f6', margin: '0 0 10px 0'}}>2. PMKSY (Drip Irrigation)</h3>
              <p style={{color: 'var(--text-muted)', fontSize: '0.9rem', margin: 0, lineHeight: '1.5'}}>Pradhan Mantri Krishi Sinchayee Yojana. Offers up to 55% subsidy for small/marginal farmers on the installation of advanced micro and drip irrigation systems.</p>
          </div>
          <div style={{background: 'rgba(255,255,255,0.03)', padding: '25px', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)'}}>
              <h3 style={{color: '#10b981', margin: '0 0 10px 0'}}>3. NABARD Refinance</h3>
              <p style={{color: 'var(--text-muted)', fontSize: '0.9rem', margin: 0, lineHeight: '1.5'}}>Provides structured project financing templates. Banks issue term loans at concessional rates (often with subventions) based directly on NABARD's approved unit costs.</p>
          </div>
      </div>

      <div style={{marginTop: '30px', padding: '20px', background: 'rgba(16, 185, 129, 0.1)', borderRadius: '12px', borderLeft: '4px solid #10b981'}}>
          <h4 style={{margin: '0 0 8px 0', color: 'white', fontSize: '1.1rem'}}>How to Apply & Secure Funding:</h4>
          <ol style={{color: 'var(--text-muted)', margin: 0, paddingLeft: '20px', fontSize: '0.95rem', lineHeight: '1.7'}}>
              <li>Register your business profile on the central MIDH portal or visit your local State Horticulture Board physical office.</li>
              <li>Procure your official land records (e.g., 7/12 extract), Aadhaar Card, Pan Card, and soil testing reports.</li>
              <li>Use the slider numbers generated by this tool to build a comprehensive Detailed Project Report (DPR).</li>
              <li>Submit the DPR to a NABARD-affiliated commercial bank branch to initiate the loan and subsidy integration process.</li>
          </ol>
      </div>
    </div>
  );
}
